prometheus:
  user: prometheus
  group: prometheus
  server:
    listen_address: 127.0.0.1:9090
    version: 1.4.1.linux-amd64
    install_dir: /opt
    source: https://github.com/prometheus/prometheus/releases/download/v1.4.1/prometheus-1.4.1.linux-amd64.tar.gz
    source_hash: sha1=3e78173e7d65623e79e0292da16e6155de947185
    args:
      config_file: /etc/prometheus/prometheus.yml
      storage:
        local_path: /var/lib/prometheus/metrics
  alertmanager:
    version: 0.5.1.linux-amd64
    install_dir: /opt
    source: https://github.com/prometheus/alertmanager/releases/download/v0.5.1/alertmanager-0.5.1.linux-amd64.tar.gz
    source_hash: sha1=8f82ccc0db806991256084faee9335353d8e3f0d
    args:
      config_file: /etc/alertmanager/alertmanager.yml
      storage:
        path: /var/lib/alertmanager
  exporter:
    node:
      version: 0.13.0.linux-amd64
      install_dir: /opt
      source: https://github.com/prometheus/node_exporter/releases/download/v0.13.0/node_exporter-0.13.0.linux-amd64.tar.gz
      source_hash: sha1=84ca5f711962319f6f7823208b9d867ab1c0e3e7
      listen_address: 127.0.0.1:9100
    postgres:
      version: v0.4.8_linux-amd64
      install_dir: /opt
      source: https://github.com/femaref/postgres_exporter/releases/download/v0.4.8/postgres_exporter_v0.4.8_linux-amd64.tar.gz
      source_hash: https://github.com/femaref/postgres_exporter/releases/download/v0.4.8/postgres_exporter_v0.4.8_linux-amd64.tar.gz.sha1
      listen_address: 127.0.0.1:9187
    blackbox:
      version: 0.3.0.linux-amd64
      install_dir: /opt
      source: https://github.com/prometheus/blackbox_exporter/releases/download/v0.3.0/blackbox_exporter-0.3.0.linux-amd64.tar.gz
      source_hash: sha1=89ac98c062315ba35eda257ca88c8c4b43f38d47
      args:
        config_file: /etc/prometheus/blackbox_exporter.yml
    haproxy:
      version: 0.7.1.linux-amd64
      install_dir: /opt
      source: https://github.com/prometheus/haproxy_exporter/releases/download/v0.7.1/haproxy_exporter-0.7.1.linux-amd64.tar.gz
      source_hash: sha1=56849253e280db3db2aa80f1013ecfe242536d32
      args:
        scrape_uri: 'unix:/run/haproxy/admin.sock'
    rabbitmq:
      version: 0.24.0.linux-amd64
      install_dir: /opt
      source: https://github.com/kbudde/rabbitmq_exporter/releases/download/v0.24.0/rabbitmq_exporter-0.24.0.linux-amd64.tar.gz
      source_hash: sha256=dbbd44a5a4b4a22ba338b9732c014587bc11513a5d6d2e3e519fc313b1cc46d4
